fix: return kerrors' ErrNoMoreInstance when do discovery but no instance
kitex-contrib/registry-eureka pull request #8
Opened 2022-02-28 15:27 UTC by codingxh

- en: 
   -  Remove `time.Sleep(30 * time.Second)` in unit tests
   -  Correct argument position in `assert.Equal()` assertion
   -  Modify the `error` that needs to be returned when the instance is empty to `kerrors.ErrNoMoreInstance`
- zh: 
   -  去除单元测试中的`time.Sleep(30 * time.Second)`
   -  纠正`assert.Equal()`断言中的参数位置
   -  修改当实例为空时所需要返回的`error`为`kerrors.ErrNoMoreInstance`

2022-02-28 15:30 UTC, codingxh commented
hello,everyOne,this mr need the first mr (https://github.com/kitex-contrib/registry-eureka/pull/7) succeed to approve ci

2022-03-01 14:35 UTC, li-jin-gou commented on resolver/resolver.go
> +		if errors.As(err, &fargo.AppNotFoundError{}) {
这里为什么不用 errors.Is ??

2022-03-01 14:35 UTC, li-jin-gou commented on docker-compose.yml
>    eureka:
空行加一下吧

2022-03-01 14:35 UTC, li-jin-gou commented on discovery_test.go
> +	"github.com/cloudwego/kitex/pkg/kerrors"
麻烦,更新一下 kitex 的版本吧,感谢。

2022-03-01 15:08 UTC, codingxh commented on docker-compose.yml
>    eureka:
no problem

2022-03-02 07:44 UTC, simon0-o requested changes

2022-03-02 08:49 UTC, codingxh commented on discovery_test.go
> +
OK

2022-03-02 13:27 UTC, codingxh commented on discovery_test.go
> +
hello, @simon0-o, it's done

2022-03-03 02:13 UTC, GuangmingLuo approved these changes

2022-03-03 03:31 UTC, li-jin-gou approved these changes

2022-03-03 05:36 UTC, li-jin-gou commented on discovery_test.go
> +
@codingxh  24 的空行去掉了,但是下面还有
预期效果应该是这样:
```
	"context"
	"io"
	"net"
	"testing"
	"time"

	"github.com/cloudwego/kitex/pkg/registry"
	"github.com/cloudwego/kitex/pkg/rpcinfo"
	registry2 "github.com/kitex-contrib/registry-eureka/registry"
	"github.com/kitex-contrib/registry-eureka/resolver"
	"github.com/stretchr/testify/assert"
```

2022-03-03 09:56 UTC, merged